# Generated by Django 2.2 on 2023-09-29 01:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('Management', '0001_initial'), ('Management', '0002_speciality_status'), ('Management', '0003_auto_20230916_2344'), ('Management', '0004_auto_20230917_0127'), ('Management', '0005_auto_20230917_2329'), ('Management', '0006_auto_20230919_1820'), ('Management', '0007_auto_20230919_1859'), ('Management', '0008_auto_20230920_1823'), ('Management', '0009_doctors_reception'), ('Management', '0010_doctors_speciality'), ('Management', '0011_appointments_doctor'), ('Management', '0012_leftpanel'), ('Management', '0013_auto_20230922_2213'), ('Management', '0014_auto_20230922_2230'), ('Management', '0015_leftpanel_icon'), ('Management', '0016_management'), ('Management', '0017_auto_20230924_1824'), ('Management', '0018_auto_20230925_1735'), ('Management', '0019_appointments_time'), ('Management', '0020_auto_20230925_1834'), ('Management', '0021_remove_doctors_capacity'), ('Management', '0022_auto_20230925_2334'), ('Management', '0023_auto_20230925_2335'), ('Management', '0024_remove_appointments_patientapproval'), ('Management', '0025_prescription_instruction'), ('Management', '0026_management_user'), ('Management', '0027_payment_paymentstatus'), ('Management', '0028_auto_20230928_0021'), ('Management', '0029_payment_fees'), ('Management', '0030_auto_20230928_0027'), ('Management', '0031_auto_20230928_1648'), ('Management', '0032_auto_20230928_1944'), ('Management', '0033_appointments_paystatus')]

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'staff_records',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Leftpanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=200)),
                ('Patient', models.BooleanField(default=False)),
                ('Staff', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('icon', models.CharField(default=True, max_length=200)),
            ],
        ),
        migrations.AlterModelTable(
            name='leftpanel',
            table='leftpanel_records',
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Speciality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.time')),
                ('reception', models.BooleanField(default=False)),
                ('speciality', models.CharField(default=0, max_length=200)),
            ],
            options={
                'db_table': 'doctors_records',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.SmallIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Appointments')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Patients')),
                ('instruction', models.TextField(null=True)),
            ],
            options={
                'db_table': 'prescription_records',
            },
        ),
        migrations.RenameField(
            model_name='leftpanel',
            old_name='Heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='leftpanel',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='leftpanel',
            old_name='Staff',
            new_name='staff',
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'department_names',
            },
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'schedule_time',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('exist', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_records',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('issuetime', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Appointments')),
                ('paymentstatus', models.BooleanField(default=False)),
                ('lastname', models.CharField(default=0, max_length=200)),
                ('fees', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'payment_records',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('problem', models.CharField(max_length=200)),
                ('medical', models.TextField(null=True)),
                ('registerdate', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('new', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('docapproval', models.BooleanField(default=False)),
                ('reason', models.TextField(max_length=400, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Patients')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.doctors')),
                ('time', models.TextField(default=0)),
                ('paystatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'appointment_records',
            },
        ),
    ]
