# Generated by Django 2.2 on 2023-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_squashed_0033_appointments_paystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftpanel',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='speciality',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lastname',
            field=models.CharField(max_length=200),
        ),
    ]
