# Generated by Django 2.2 on 2023-09-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
