# Generated by Django 2.2 on 2023-10-01 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='user',
            field=models.ManyToManyField(through='Management.Roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
