# Generated by Django 2.2 on 2023-09-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
