# Generated by Django 2.2 on 2023-09-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='doctors',
            name='lastname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='lastname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
