# Generated by Django 2.2 on 2023-09-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_patients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
