# Generated by Django 2.2 on 2023-09-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20230929_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='recepapproval',
            field=models.BooleanField(default=False),
        ),
    ]
