# Generated by Django 2.2 on 2023-09-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20230915_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='appointments',
            name='lastname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
