# Generated by Django 2.2 on 2023-09-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20230915_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='username',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='username',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
