# Generated by Django 2.2 on 2023-09-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_appointments_recepapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftpanel',
            name='management',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Management'),
        ),
    ]
