# Generated by Django 2.2 on 2023-09-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_patients_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
