# Generated by Django 2.2 on 2023-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_leftpanel_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftpanel',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='leftpanel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='leftpanel',
            name='staff',
        ),
    ]
