# Generated by Django 2.2 on 2023-09-17 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20230917_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'schedule_time',
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.time'),
            preserve_default=False,
        ),
    ]
