# Generated by Django 2.2 on 2023-09-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_speciality'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='speciality',
            table='department_names',
        ),
    ]
