# Generated by Django 2.2 on 2023-09-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20230912_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='Phoneno',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='password',
        ),
    ]
