# Generated by Django 2.2 on 2023-09-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20230919_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='user',
            new_name='patient',
        ),
    ]
