# Generated by Django 2.2 on 2023-09-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20230916_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='special',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Management.Speciality'),
            preserve_default=False,
        ),
    ]
