# Generated by Django 2.2 on 2023-09-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20230919_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.time'),
        ),
    ]
