# Generated by Django 2.2 on 2023-09-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20230912_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='problem',
        ),
    ]
