# Generated by Django 2.2 on 2023-09-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20230920_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='reception',
            field=models.BooleanField(default=False),
        ),
    ]
