# Generated by Django 2.2 on 2023-09-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20230916_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Speciality'),
        ),
    ]
