# Generated by Django 2.2 on 2023-09-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_remove_patients_problem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctors',
            table='doctors_records',
        ),
    ]
