# Generated by Django 2.2 on 2023-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_doctors_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='speciality',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
