# Generated by Django 2.2 on 2023-09-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_doctors_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.doctors'),
        ),
    ]
