# Generated by Django 2.2 on 2023-09-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
