# Generated by Django 2.2 on 2023-09-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_appointments_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leftpanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=200)),
                ('Patient', models.BooleanField(default=False)),
                ('Staff', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
