# Generated by Django 2.2 on 2023-09-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_appointments_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='new',
            new_name='exist',
        ),
    ]
