# Generated by Django 2.2 on 2023-09-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_auto_20230913_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='doctorid',
            field=models.IntegerField(null=True),
        ),
    ]
