# Generated by Django 2.2 on 2023-09-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_leftpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='leftpanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Leftpanel'),
        ),
        migrations.AddField(
            model_name='patients',
            name='leftpanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Leftpanel'),
        ),
    ]
