# Generated by Django 2.2 on 2023-09-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_patients_doctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='prescription',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
