# Generated by Django 2.2 on 2023-09-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_auto_20230922_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='leftpanel',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='leftpanel',
        ),
    ]
