# Generated by Django 2.2 on 2023-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_appointments_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='doctorid',
        ),
        migrations.AddField(
            model_name='appointments',
            name='medicalhistory',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='doctor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
