# Generated by Django 2.2 on 2023-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_auto_20230922_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftpanel',
            name='icon',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
