# Generated by Django 2.2 on 2023-09-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20230913_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Registerdate',
            field=models.DateField(),
        ),
    ]
