# Generated by Django 2.2 on 2023-09-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_management'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leftpanel',
            table='leftpanel_records',
        ),
    ]
