# Generated by Django 2.2 on 2023-09-13 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_auto_20230913_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='docapproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patientapproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('issuetime', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Appointments')),
            ],
        ),
    ]
