# Generated by Django 2.2 on 2023-09-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_auto_20230924_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='prescription',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.SmallIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Appointments')),
            ],
            options={
                'db_table': 'prescription_records',
            },
        ),
    ]
