# Generated by Django 2.2 on 2023-09-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_auto_20230913_2159'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment_records',
        ),
    ]
