# Generated by Django 2.2 on 2023-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_auto_20230925_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='time',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
