# Generated by Django 2.2 on 2023-09-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_auto_20230913_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='medicalhistory',
        ),
    ]
