# Generated by Django 2.2 on 2023-09-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0019_appointments_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='capacity',
        ),
        migrations.AddField(
            model_name='doctors',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
