# Generated by Django 2.2 on 2023-09-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0020_auto_20230925_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='capacity',
        ),
    ]
