# Generated by Django 2.2 on 2023-09-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0022_auto_20230925_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Patients'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Appointments'),
        ),
    ]
