# Generated by Django 2.2 on 2023-09-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0023_auto_20230925_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patientapproval',
        ),
    ]
