# Generated by Django 2.2 on 2023-09-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0024_remove_appointments_patientapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instruction',
            field=models.TextField(null=True),
        ),
    ]
