# Generated by Django 2.2 on 2023-09-27 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0025_prescription_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
