# Generated by Django 2.2 on 2023-09-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0026_management_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentstatus',
            field=models.BooleanField(default=False),
        ),
    ]
