# Generated by Django 2.2 on 2023-09-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0027_payment_paymentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='payment',
            name='lastname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
