# Generated by Django 2.2 on 2023-09-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0028_auto_20230928_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
