# Generated by Django 2.2 on 2023-09-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0029_payment_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Registerdate',
            new_name='registerdate',
        ),
        migrations.RenameField(
            model_name='leftpanel',
            old_name='Heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='leftpanel',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='leftpanel',
            old_name='Staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='management',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='Time',
            new_name='time',
        ),
    ]
