# Generated by Django 2.2 on 2023-09-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0030_auto_20230928_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='Age',
            new_name='age',
        ),
    ]
