# Generated by Django 2.2 on 2023-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0031_auto_20230928_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='issuetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
