# Generated by Django 2.2 on 2023-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0032_auto_20230928_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='paystatus',
            field=models.BooleanField(default=False),
        ),
    ]
